### ISSUE TITLE
about epoch

### ISSUE THREAD

**Issue by yinguanchun** [xmed-lab/DHC#5]
Hello, the training epoch of synapse in code is 500，but it is 300 in the paper. I want to know the epoch of Synapse and AMOS. 
Tranks!

**Comment by yinguanchun** [comment]
if my understanding of the code is not wrong, I find that the size of the data does not change during the training phase, but the height and width become half of the original when interfering, is there any reason for this operation？

**Comment by McGregorWwww** [comment]
Hi, 

1. for the number of epochs, there's no major difference since we use early stopping strategy, the training will be ended around 200 epochs.
2. we use the clip range following previous works such TransUNet.
3. the size of the data is also changed in augmentations during training, it's for reducing the GPU costs.
